apiVersion: batch/v1
kind: Job
metadata:
  name: comida
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: comida
        image: mrprofile/comida.console.poc:v1
      restartPolicy: Never
  backoffLimit: 4